/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.haui.ui;

import com.haui.model.DeTai;
import com.haui.service.ReportService;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Minh Tuyen
 */
public class DeTaiForm extends javax.swing.JPanel {

    /**
     * Creates new form DeTaiForm
     */
    private final com.haui.service.DataService service = AppContext.DATA_SERVICE;
    private DefaultTableModel tableModel;

    public DeTaiForm() {
        initComponents();
        setupAfterInit();
        loadTable(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMaDT = new javax.swing.JLabel();
        txtMaDT = new javax.swing.JTextField();
        lblTenDT = new javax.swing.JLabel();
        txtTenDT = new javax.swing.JTextField();
        lblGiangVien = new javax.swing.JLabel();
        txtGiangVien = new javax.swing.JTextField();
        lblMSSV = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblNgayBD = new javax.swing.JLabel();
        txtNgayBD = new javax.swing.JTextField();
        lblNgayKT = new javax.swing.JLabel();
        txtNgayKT = new javax.swing.JTextField();
        lblTrangThai = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        lblMoTa = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JScrollPane();
        txtMoTaArea = new javax.swing.JTextArea();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXuatBC = new javax.swing.JButton();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeTai = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();

        lblMaDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaDT.setText("Mã đề tài :");

        lblTenDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTenDT.setText("Tên đề tài : ");

        txtTenDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDTActionPerformed(evt);
            }
        });

        lblGiangVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGiangVien.setText("Giảng viên HD :");

        lblMSSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMSSV.setText("MSSV :");

        lblHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHoTen.setText("Họ tên SV :");

        lblNgayBD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNgayBD.setText("Ngày bắt đầu (dd/MM/yyyy) :");

        lblNgayKT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNgayKT.setText("Ngày kết thúc (dd/MM/yyyy) :");

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTrangThai.setText("Trạng thái :");

        cboTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mới", "Đang thực hiện", "Tạm dừng", "Hoàn thành" }));

        lblMoTa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMoTa.setText("Mô tả :");

        txtMoTaArea.setColumns(20);
        txtMoTaArea.setRows(5);
        txtMoTa.setViewportView(txtMoTaArea);

        btnThem.setBackground(new java.awt.Color(0, 90, 170));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("+ Thêm");

        btnSua.setBackground(new java.awt.Color(230, 87, 37));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");

        btnXoa.setBackground(new java.awt.Color(239, 68, 68));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");

        btnLamMoi.setBackground(new java.awt.Color(100, 116, 139));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm mới");

        btnXuatBC.setBackground(new java.awt.Color(0, 204, 255));
        btnXuatBC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXuatBC.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatBC.setText("Xuất BC");

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTimKiem.setText("Tìm kiếm :");

        tblDeTai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã DT", "Tên đề tài", "Giảng viên", "MSSV", "Sinh viên", "Trạng thái", "Tiến độ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDeTai);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 255));
        lblTitle.setText("Quản lý đề tài");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMoTa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE))
                        .addContainerGap(168, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMSSV)
                                .addGap(343, 343, 343)
                                .addComponent(lblHoTen))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMoTa)
                            .addComponent(lblGiangVien)
                            .addComponent(txtGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblNgayBD)
                                            .addGap(127, 127, 127))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtMaDT, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtMSSV, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtNgayBD, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(103, 103, 103)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMaDT, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(215, 215, 215)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTenDT, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNgayKT, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtHoTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                        .addComponent(txtNgayKT, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(211, 211, 211)
                                        .addComponent(lblTenDT, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblTimKiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSua)
                                        .addGap(51, 51, 51)
                                        .addComponent(btnXoa)
                                        .addGap(51, 51, 51)
                                        .addComponent(btnLamMoi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnXuatBC)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaDT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenDT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblGiangVien)
                .addGap(18, 18, 18)
                .addComponent(txtGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMSSV)
                    .addComponent(lblHoTen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayBD)
                    .addComponent(lblNgayKT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrangThai)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMoTa)
                .addGap(18, 18, 18)
                .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatBC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDTActionPerformed
    // ================== PHẦN NGHIỆP VỤ ==================

    private void setupAfterInit() {
        tableModel = (DefaultTableModel) tblDeTai.getModel();

        // Renderer màu cho cột Trạng thái (cột 5) và Tiến độ (cột 6)
        tblDeTai.getColumnModel().getColumn(5) // Trạng thái
                .setCellRenderer(new TableRenderers.TrangThaiRenderer());
        tblDeTai.getColumnModel().getColumn(6) // Tiến độ
                .setCellRenderer(new TableRenderers.TienDoRenderer());

        // Khi chọn 1 dòng trong bảng -> hiển thị lên form
        tblDeTai.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                hienThiLenForm();
            }
        });

        // Tìm kiếm realtime khi gõ vào ô txtTimKiem
        txtTimKiem.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                loadTable(txtTimKiem.getText());
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                loadTable(txtTimKiem.getText());
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                loadTable(txtTimKiem.getText());
            }
        });

        // Gắn sự kiện cho 5 nút 
        btnThem.addActionListener(this::btnThemActionPerformed);
        btnSua.addActionListener(this::btnSuaActionPerformed);
        btnXoa.addActionListener(this::btnXoaActionPerformed);
        btnLamMoi.addActionListener(this::btnLamMoiActionPerformed);
        btnXuatBC.addActionListener(this::btnXuatBCActionPerformed);

        // Căn giữa tất cả các cột
        javax.swing.table.DefaultTableCellRenderer centerRenderer
                = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        for (int i = 0; i < tblDeTai.getColumnCount(); i++) {
            tblDeTai.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        tblDeTai.getColumnModel().getColumn(5) // cột Trạng thái
                .setCellRenderer(new TableRenderers.TrangThaiRenderer());
        tblDeTai.getColumnModel().getColumn(6) // cột Tiến độ
                .setCellRenderer(new TableRenderers.TienDoRenderer());
        tblDeTai.setRowHeight(32);
        tblDeTai.setShowGrid(true);
        tblDeTai.setGridColor(new java.awt.Color(180, 190, 205));

        //tool tip cho các nút
        btnThem.setToolTipText("Thêm đề tài mới");
        btnSua.setToolTipText("Sửa đề tài đang chọn");
        btnXoa.setToolTipText("Xóa đề tài đang chọn");
        btnLamMoi.setToolTipText("Xóa trắng form nhập liệu");
        btnXuatBC.setToolTipText("Xuất báo cáo đề tài ra file .txt");

        // Placeholder ô tìm kiếm
        txtTimKiem.setText("Tìm theo mã DT hoặc tên đề tài...");
        txtTimKiem.setForeground(java.awt.Color.GRAY);

        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtTimKiem.getText().equals("Tìm theo mã DT hoặc tên đề tài...")) {
                    txtTimKiem.setText("");
                    txtTimKiem.setForeground(java.awt.Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtTimKiem.getText().isEmpty()) {
                    txtTimKiem.setText("Tìm theo mã DT hoặc tên đề tài...");
                    txtTimKiem.setForeground(java.awt.Color.GRAY);
                }
            }
        });
    }

    /**
     * Nạp dữ liệu vào bảng. keyword = null -> hiển thị tất cả
     */
    public void loadTable(String keyword) {
        if (keyword != null && keyword.startsWith("Tìm theo")) {
            keyword = null;
        }
        tableModel.setRowCount(0);
        java.util.Collection<DeTai> data = (keyword == null || keyword.isBlank())
                ? service.layTatCa()
                : service.timKiem(keyword);
        for (DeTai dt : data) {
            tableModel.addRow(new Object[]{
                dt.getMaDT(), dt.getTenDT(), dt.getGiangVien(),
                dt.getMssv(), dt.getHoTenSV(), dt.getTrangThai(), dt.getTienDo()
            });
        }
    }

    /**
     * Khi chọn dòng trong bảng -> điền dữ liệu lên các ô input
     */
    private void hienThiLenForm() {
        int row = tblDeTai.getSelectedRow();
        if (row == -1) {
            return;
        }
        String ma = tableModel.getValueAt(row, 0).toString();
        DeTai dt = service.timTheoMa(ma);
        if (dt == null) {
            return;
        }
        txtMaDT.setText(dt.getMaDT());
        txtTenDT.setText(dt.getTenDT());
        txtGiangVien.setText(dt.getGiangVien());
        txtMSSV.setText(dt.getMssv());
        txtHoTen.setText(dt.getHoTenSV());
        txtNgayBD.setText(dt.getNgayBatDau());
        txtNgayKT.setText(dt.getNgayKetThuc());
        txtMoTaArea.setText(dt.getMoTa());
        cboTrangThai.setSelectedItem(dt.getTrangThai());
    }

    /**
     * Xóa trắng toàn bộ form nhập liệu
     */
    private void clearForm() {
        txtMaDT.setText("");
        txtTenDT.setText("");
        txtGiangVien.setText("");
        txtMSSV.setText("");
        txtHoTen.setText("");
        txtNgayBD.setText("");
        txtNgayKT.setText("");
        txtMoTaArea.setText("");
        cboTrangThai.setSelectedIndex(0);
        tblDeTai.clearSelection();
        txtMaDT.requestFocus();
    }

    // ---- Xử lý 5 nút ----
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {
        String ma = txtMaDT.getText().trim();
        String ten = txtTenDT.getText().trim();
        String gv = txtGiangVien.getText().trim();
        String mssv = txtMSSV.getText().trim();

        if (ma.isEmpty() || ten.isEmpty() || gv.isEmpty() || mssv.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng nhập đầy đủ các trường dữ liệu.",
                    "Thiếu thông tin", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Validate mã DT không có khoảng trắng
        if (ma.contains(" ")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Mã đề tài không được chứa khoảng trắng!",
                    "Lỗi", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validate MSSV chỉ được nhập số
        if (!mssv.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "MSSV chỉ được nhập số!",
                    "Lỗi", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validate ngày tháng
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false); // không chấp nhận ngày kiểu 32/13/2024

        String ngayBD = txtNgayBD.getText().trim();
        String ngayKT = txtNgayKT.getText().trim();

        if (!ngayBD.isEmpty()) {
            try {
                sdf.parse(ngayBD);
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Ngày bắt đầu không đúng định dạng dd/MM/yyyy!",
                        "Lỗi định dạng", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        if (!ngayKT.isEmpty()) {
            try {
                sdf.parse(ngayKT);
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Ngày kết thúc không đúng định dạng dd/MM/yyyy!",
                        "Lỗi định dạng", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        // Validate ngày kết thúc phải sau ngày bắt đầu
        if (!ngayBD.isEmpty() && !ngayKT.isEmpty()) {
            try {
                java.util.Date dBD = sdf.parse(ngayBD);
                java.util.Date dKT = sdf.parse(ngayKT);
                if (!dKT.after(dBD)) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Ngày kết thúc phải sau ngày bắt đầu!",
                            "Lỗi ngày tháng", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception e) {

            }
        }

        DeTai dt = new DeTai(ma, ten, gv, mssv);
        dt.setHoTenSV(txtHoTen.getText().trim());
        dt.setNgayBatDau(txtNgayBD.getText().trim());
        dt.setNgayKetThuc(txtNgayKT.getText().trim());
        dt.setMoTa(txtMoTaArea.getText().trim());
        dt.setTrangThai((String) cboTrangThai.getSelectedItem());

        if (service.themDeTai(dt)) {
            loadTable(null);
            clearForm();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Thêm đề tài \"" + ma + "\" thành công!",
                    "Thành công", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            AppContext.MAIN_FRAME.refreshAll();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Mã đề tài \"" + ma + "\" đã tồn tại trong hệ thống!",
                    "Trùng mã", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {
        String ma = txtMaDT.getText().trim();
        if (ma.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn đề tài cần sửa từ bảng bên dưới.",
                    "Chưa chọn đề tài", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String mssv = txtMSSV.getText().trim();
        // Validate mã DT không có khoảng trắng
        if (ma.contains(" ")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Mã đề tài không được chứa khoảng trắng!",
                    "Lỗi", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validate MSSV chỉ được nhập số
        if (!mssv.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "MSSV chỉ được nhập số!",
                    "Lỗi", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validate kiểm tra ngày tháng ngày tháng
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false); // không chấp nhận ngày kiểu 32/13/2024

        String ngayBD = txtNgayBD.getText().trim();
        String ngayKT = txtNgayKT.getText().trim();

        if (!ngayBD.isEmpty()) {
            try {
                sdf.parse(ngayBD);
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Ngày bắt đầu không đúng định dạng dd/MM/yyyy!",
                        "Lỗi định dạng", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        if (!ngayKT.isEmpty()) {
            try {
                sdf.parse(ngayKT);
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Ngày kết thúc không đúng định dạng dd/MM/yyyy!",
                        "Lỗi định dạng", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        // Validate ngày kết thúc phải sau ngày bắt đầu
        if (!ngayBD.isEmpty() && !ngayKT.isEmpty()) {
            try {
                java.util.Date dBD = sdf.parse(ngayBD);
                java.util.Date dKT = sdf.parse(ngayKT);
                if (!dKT.after(dBD)) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Ngày kết thúc phải sau ngày bắt đầu!",
                            "Lỗi ngày tháng", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (Exception e) {

            }
        }
        DeTai dt = new DeTai(ma, txtTenDT.getText().trim(),
                txtGiangVien.getText().trim(), mssv);
        dt.setHoTenSV(txtHoTen.getText().trim());
        dt.setNgayBatDau(txtNgayBD.getText().trim());
        dt.setNgayKetThuc(txtNgayKT.getText().trim());
        dt.setMoTa(txtMoTaArea.getText().trim());
        dt.setTrangThai((String) cboTrangThai.getSelectedItem());

        if (service.suaDeTai(dt)) {
            loadTable(null);
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Cập nhật đề tài \"" + ma + "\" thành công!",
                    "Thành công", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            AppContext.MAIN_FRAME.refreshAll();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Không tìm thấy đề tài \"" + ma + "\" trong hệ thống!",
                    "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {
        String ma = txtMaDT.getText().trim();
        if (ma.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn đề tài cần xóa từ bảng bên dưới.",
                    "Chưa chọn đề tài", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn xóa đề tài \"" + ma + "\" không?",
                "Xác nhận xóa",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        service.xoaDeTai(ma);
        loadTable(null);
        clearForm();
        AppContext.MAIN_FRAME.refreshAll();
    }

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {
        clearForm();
    }

    private void btnXuatBCActionPerformed(java.awt.event.ActionEvent evt) {
        String ma = txtMaDT.getText().trim();
        DeTai dt = service.timTheoMa(ma);
        if (dt == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn đề tài từ bảng trước khi xuất báo cáo.",
                    "Chưa chọn đề tài", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        String file = new ReportService().export(dt);
        if (file != null) {
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Xuất báo cáo thành công!\nFile: " + file + "\n\nBạn có muốn mở file ngay không?",
                    "Thành công",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                try {
                    java.awt.Desktop.getDesktop().open(new java.io.File(file));
                } catch (java.io.IOException ex) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Không thể mở file:\n" + ex.getMessage(),
                            "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Xuất báo cáo thất bại. Vui lòng kiểm tra quyền ghi file hoặc thử lại.",
                    "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatBC;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGiangVien;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMSSV;
    private javax.swing.JLabel lblMaDT;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblNgayBD;
    private javax.swing.JLabel lblNgayKT;
    private javax.swing.JLabel lblTenDT;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JTable tblDeTai;
    private javax.swing.JTextField txtGiangVien;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMSSV;
    private javax.swing.JTextField txtMaDT;
    private javax.swing.JScrollPane txtMoTa;
    private javax.swing.JTextArea txtMoTaArea;
    private javax.swing.JTextField txtNgayBD;
    private javax.swing.JTextField txtNgayKT;
    private javax.swing.JTextField txtTenDT;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
