/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.haui.ui;

import com.haui.model.DeTai;

/**
 *
 * @author Minh Tuyen
 */
public class ProgressForm extends javax.swing.JPanel {

    /**
     * Creates new form ProgressForm
     */
    public ProgressForm() {
        initComponents();
        setupAfterInit();
        loadCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // ================== PHẦN NGHIỆP VỤ (TỰ VIẾT) ==================
    private com.haui.model.DeTai current;

    private void setupAfterInit() {
        // Gắn sự kiện cho ComboBox: khi đổi đề tài -> hiển thị thông tin
        cboDeTai.addActionListener(e -> hienThiTienDo());

        // Gắn sự kiện cho 4 checkbox: khi tick -> cập nhật % và màu
        chkDeCuong.addActionListener(e -> capNhatThanhTienDo());
        chkThuThap.addActionListener(e -> capNhatThanhTienDo());
        chkCodeDemo.addActionListener(e -> capNhatThanhTienDo());
        chkBaoCao.addActionListener(e -> capNhatThanhTienDo());

        // Gắn sự kiện cho nút Lưu
        btnLuuTienDo.addActionListener(this::btnLuuTienDoActionPerformed);

        progressBar.setMinimum(0);
        progressBar.setMaximum(100);
    }

    /**
     * Nạp danh sách đề tài vào ComboBox
     */
    public void loadCombo() {
        cboDeTai.removeAllItems();
        for (com.haui.model.DeTai dt : AppContext.DATA_SERVICE.layTatCa()) {
            cboDeTai.addItem(dt.getMaDT() + " - " + dt.getTenDT());
        }
        hienThiTienDo();
    }

    /**
     * Khi đổi đề tài trong ComboBox -> hiển thị thông tin + trạng thái checkbox
     */
    private void hienThiTienDo() {
        String sel = (String) cboDeTai.getSelectedItem();
        if (sel == null || sel.isBlank()) {
            current = null;
            return;
        }
        String ma = sel.contains("-") ? sel.split("-")[0].trim() : sel.trim();
        current = AppContext.DATA_SERVICE.timTheoMa(ma);
        if (current == null) {
            return;
        }

        lblTenDTVal.setText("Tên đề tài: " + current.getTenDT());
        lblGiangVienVal.setText("Giảng viên: " + current.getGiangVien());
        lblTrangThaiVal.setText("Trạng thái: " + current.getTrangThai());

        chkDeCuong.setSelected(current.isDeCuong());
        chkThuThap.setSelected(current.isThuThapDuLieu());
        chkCodeDemo.setSelected(current.isCodeDemo());
        chkBaoCao.setSelected(current.isVietBaoCao());

        capNhatThanhTienDo();
    }

    /**
     * Cập nhật thanh tiến độ và % khi tick checkbox
     */
    private void capNhatThanhTienDo() {
        int done = 0;
        if (chkDeCuong.isSelected()) {
            done++;
        }
        if (chkThuThap.isSelected()) {
            done++;
        }
        if (chkCodeDemo.isSelected()) {
            done++;
        }
        if (chkBaoCao.isSelected()) {
            done++;
        }
        int pct = done * 25;

        progressBar.setValue(pct);
        lblPhanTram.setText(pct + "%");

        java.awt.Color c = pct == 100
                ? new java.awt.Color(22, 163, 74)
                : pct >= 50
                        ? new java.awt.Color(230, 87, 37)
                        : new java.awt.Color(239, 68, 68);
        progressBar.setForeground(c);
        lblPhanTram.setForeground(c);
    }

    private void btnLuuTienDoActionPerformed(java.awt.event.ActionEvent evt) {
        if (current == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn đề tài trước khi lưu tiến độ.",
                    "Chưa chọn đề tài", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        current.setDeCuong(chkDeCuong.isSelected());
        current.setThuThapDuLieu(chkThuThap.isSelected());
        current.setCodeDemo(chkCodeDemo.isSelected());
        current.setVietBaoCao(chkBaoCao.isSelected());
        AppContext.JSON_SERVICE.save(AppContext.DATA_SERVICE.layTatCa());
        AppContext.MAIN_FRAME.refreshAll();
        javax.swing.JOptionPane.showMessageDialog(this,
                "Đã lưu tiến độ đề tài \"" + current.getMaDT() + "\" thành công!",
                "Thành công", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGiaiDoan1 = new javax.swing.JPanel();
        lblMoTa1 = new javax.swing.JLabel();
        lblTrangThai1 = new javax.swing.JLabel();
        chkDeCuong = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        pnlGiaiDoan2 = new javax.swing.JPanel();
        chkThuThap = new javax.swing.JCheckBox();
        lblMoTa2 = new javax.swing.JLabel();
        lblTrangThai2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pnlGiaiDoan3 = new javax.swing.JPanel();
        lblTrangThai3 = new javax.swing.JLabel();
        chkCodeDemo = new javax.swing.JCheckBox();
        lblMoTa3 = new javax.swing.JLabel();
        pnlGiaiDoan4 = new javax.swing.JPanel();
        lblMoTa4 = new javax.swing.JLabel();
        lblTrangThai4 = new javax.swing.JLabel();
        chkBaoCao = new javax.swing.JCheckBox();
        pnlTong = new javax.swing.JPanel();
        lblChonDeTai = new javax.swing.JLabel();
        cboDeTai = new javax.swing.JComboBox<>();
        lblTenDTVal = new javax.swing.JLabel();
        lblGiangVienVal = new javax.swing.JLabel();
        lblTrangThaiVal = new javax.swing.JLabel();
        lblTienDo = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        lblPhanTram = new javax.swing.JLabel();
        btnLuuTienDo = new javax.swing.JButton();

        pnlGiaiDoan1.setBackground(new java.awt.Color(240, 253, 244));

        lblMoTa1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMoTa1.setForeground(new java.awt.Color(255, 102, 0));
        lblMoTa1.setText("Lập kế hoạch nghiên cứu, xây dựng đề cương chi tiết");

        lblTrangThai1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrangThai1.setForeground(new java.awt.Color(22, 163, 74));
        lblTrangThai1.setText("✓ Xong");

        chkDeCuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkDeCuong.setText("Giai đoạn 1: Viết đề cương");
        chkDeCuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDeCuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGiaiDoan1Layout = new javax.swing.GroupLayout(pnlGiaiDoan1);
        pnlGiaiDoan1.setLayout(pnlGiaiDoan1Layout);
        pnlGiaiDoan1Layout.setHorizontalGroup(
            pnlGiaiDoan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiaiDoan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGiaiDoan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGiaiDoan1Layout.createSequentialGroup()
                        .addComponent(lblMoTa1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlGiaiDoan1Layout.createSequentialGroup()
                        .addComponent(chkDeCuong, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTrangThai1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        pnlGiaiDoan1Layout.setVerticalGroup(
            pnlGiaiDoan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiaiDoan1Layout.createSequentialGroup()
                .addGroup(pnlGiaiDoan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlGiaiDoan1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chkDeCuong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlGiaiDoan1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblTrangThai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMoTa1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1388, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        pnlGiaiDoan2.setBackground(new java.awt.Color(240, 253, 244));

        chkThuThap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkThuThap.setText("Giai đoạn 2: Thu thập dữ liệu");
        chkThuThap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkThuThapActionPerformed(evt);
            }
        });

        lblMoTa2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMoTa2.setForeground(new java.awt.Color(255, 102, 0));
        lblMoTa2.setText("Tìm kiếm, tổng hợp tài liệu và dữ liệu nghiên cứu ");

        lblTrangThai2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrangThai2.setForeground(new java.awt.Color(22, 163, 74));
        lblTrangThai2.setText("✓ Xong");

        javax.swing.GroupLayout pnlGiaiDoan2Layout = new javax.swing.GroupLayout(pnlGiaiDoan2);
        pnlGiaiDoan2.setLayout(pnlGiaiDoan2Layout);
        pnlGiaiDoan2Layout.setHorizontalGroup(
            pnlGiaiDoan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiaiDoan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGiaiDoan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkThuThap, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMoTa2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrangThai2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlGiaiDoan2Layout.setVerticalGroup(
            pnlGiaiDoan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiaiDoan2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(chkThuThap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMoTa2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGiaiDoan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrangThai2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        pnlGiaiDoan3.setBackground(new java.awt.Color(240, 253, 244));

        lblTrangThai3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrangThai3.setForeground(new java.awt.Color(22, 163, 74));
        lblTrangThai3.setText("✓ Xong");

        chkCodeDemo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkCodeDemo.setText("Giai đoạn 3: Code demo");
        chkCodeDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCodeDemoActionPerformed(evt);
            }
        });

        lblMoTa3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMoTa3.setForeground(new java.awt.Color(255, 102, 0));
        lblMoTa3.setText("Lập trình, xây dựng sản phẩm/demo minh chứng");

        javax.swing.GroupLayout pnlGiaiDoan3Layout = new javax.swing.GroupLayout(pnlGiaiDoan3);
        pnlGiaiDoan3.setLayout(pnlGiaiDoan3Layout);
        pnlGiaiDoan3Layout.setHorizontalGroup(
            pnlGiaiDoan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiaiDoan3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGiaiDoan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkCodeDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMoTa3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTrangThai3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );
        pnlGiaiDoan3Layout.setVerticalGroup(
            pnlGiaiDoan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGiaiDoan3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlGiaiDoan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGiaiDoan3Layout.createSequentialGroup()
                        .addComponent(chkCodeDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMoTa3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGiaiDoan3Layout.createSequentialGroup()
                        .addComponent(lblTrangThai3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );

        pnlGiaiDoan4.setBackground(new java.awt.Color(240, 253, 244));

        lblMoTa4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMoTa4.setForeground(new java.awt.Color(255, 102, 51));
        lblMoTa4.setText("Hoàn thiện báo cáo tổng kết kết quả nghiên cứu");

        lblTrangThai4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrangThai4.setForeground(new java.awt.Color(22, 163, 74));
        lblTrangThai4.setText("✓ Xong");

        chkBaoCao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkBaoCao.setText("Giai đoạn 4: Viết báo cáo");

        javax.swing.GroupLayout pnlGiaiDoan4Layout = new javax.swing.GroupLayout(pnlGiaiDoan4);
        pnlGiaiDoan4.setLayout(pnlGiaiDoan4Layout);
        pnlGiaiDoan4Layout.setHorizontalGroup(
            pnlGiaiDoan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiaiDoan4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlGiaiDoan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMoTa4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTrangThai4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        pnlGiaiDoan4Layout.setVerticalGroup(
            pnlGiaiDoan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiaiDoan4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(chkBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMoTa4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGiaiDoan4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTrangThai4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pnlTong.setBackground(new java.awt.Color(240, 253, 244));

        lblChonDeTai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChonDeTai.setText("Chọn đề tài :");

        cboDeTai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cboDeTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDeTaiActionPerformed(evt);
            }
        });

        lblTenDTVal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenDTVal.setText("Tên đề tài:");

        lblGiangVienVal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGiangVienVal.setText("Giảng viên:");

        lblTrangThaiVal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrangThaiVal.setText("Trạng thái:");

        lblTienDo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTienDo.setText("Tiến độ tổng");

        progressBar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        lblPhanTram.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblPhanTram.setForeground(new java.awt.Color(255, 0, 0));
        lblPhanTram.setText("0%");

        btnLuuTienDo.setBackground(new java.awt.Color(0, 102, 204));
        btnLuuTienDo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLuuTienDo.setText("💾 Lưu tiến độ");

        javax.swing.GroupLayout pnlTongLayout = new javax.swing.GroupLayout(pnlTong);
        pnlTong.setLayout(pnlTongLayout);
        pnlTongLayout.setHorizontalGroup(
            pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongLayout.createSequentialGroup()
                .addGroup(pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTongLayout.createSequentialGroup()
                        .addGroup(pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTongLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPhanTram, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTrangThaiVal, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGiangVienVal, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTenDTVal, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblChonDeTai)))
                            .addGroup(pnlTongLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(btnLuuTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(pnlTongLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cboDeTai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlTongLayout.setVerticalGroup(
            pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChonDeTai)
                .addGap(18, 18, 18)
                .addComponent(cboDeTai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(lblTenDTVal)
                .addGap(61, 61, 61)
                .addComponent(lblGiangVienVal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTrangThaiVal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(lblTienDo)
                .addGap(34, 34, 34)
                .addComponent(lblPhanTram)
                .addGap(38, 38, 38)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnLuuTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlGiaiDoan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlGiaiDoan3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(pnlGiaiDoan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 804, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(372, 372, 372)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(725, 725, 725)))
                        .addContainerGap(1881, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlGiaiDoan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlGiaiDoan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pnlGiaiDoan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)))
                                .addComponent(pnlGiaiDoan3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlGiaiDoan4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkDeCuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDeCuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDeCuongActionPerformed

    private void chkCodeDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCodeDemoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCodeDemoActionPerformed

    private void chkThuThapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkThuThapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkThuThapActionPerformed

    private void cboDeTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDeTaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDeTaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuTienDo;
    private javax.swing.JComboBox<String> cboDeTai;
    private javax.swing.JCheckBox chkBaoCao;
    private javax.swing.JCheckBox chkCodeDemo;
    private javax.swing.JCheckBox chkDeCuong;
    private javax.swing.JCheckBox chkThuThap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblChonDeTai;
    private javax.swing.JLabel lblGiangVienVal;
    private javax.swing.JLabel lblMoTa1;
    private javax.swing.JLabel lblMoTa2;
    private javax.swing.JLabel lblMoTa3;
    private javax.swing.JLabel lblMoTa4;
    private javax.swing.JLabel lblPhanTram;
    private javax.swing.JLabel lblTenDTVal;
    private javax.swing.JLabel lblTienDo;
    private javax.swing.JLabel lblTrangThai1;
    private javax.swing.JLabel lblTrangThai2;
    private javax.swing.JLabel lblTrangThai3;
    private javax.swing.JLabel lblTrangThai4;
    private javax.swing.JLabel lblTrangThaiVal;
    private javax.swing.JPanel pnlGiaiDoan1;
    private javax.swing.JPanel pnlGiaiDoan2;
    private javax.swing.JPanel pnlGiaiDoan3;
    private javax.swing.JPanel pnlGiaiDoan4;
    private javax.swing.JPanel pnlTong;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
