/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.haui.ui;

import com.haui.model.TaiLieu;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.UUID;

/**
 *
 * @author Minh Tuyen
 */
public class TaiLieuForm extends javax.swing.JPanel {

    /**
     * Creates new form TaiLieuForm
     */
    private DefaultTableModel tableModel;

    public TaiLieuForm() {
        initComponents();
        setupAfterInit();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnMoFile = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        scrollTable = new javax.swing.JScrollPane();
        tblTaiLieu = new javax.swing.JTable();

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTimKiem.setText("Tìm kiếm tài liệu");

        btnThem.setBackground(new java.awt.Color(0, 153, 255));
        btnThem.setText("+ Thêm file");

        btnMoFile.setBackground(new java.awt.Color(255, 102, 51));
        btnMoFile.setText("Mở file");

        btnXoa.setBackground(new java.awt.Color(255, 0, 0));
        btnXoa.setText("Xóa");

        tblTaiLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên file", "Loại", "Đề tài liên kết", "Ngày thêm", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTable.setViewportView(tblTaiLieu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollTable, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(btnMoFile)
                        .addGap(143, 143, 143)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))
                    .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoFile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // ================== PHẦN NGHIỆP VỤ  ==================

    private void setupAfterInit() {
        tableModel = (DefaultTableModel) tblTaiLieu.getModel();

        // Renderer màu cho cột "Loại" (cột số 2)
        tblTaiLieu.getColumnModel().getColumn(2)
                .setCellRenderer(new TableRenderers.LoaiRenderer());

        // Tìm kiếm realtime
        txtTimKiem.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e)  { loadTable(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e)  { loadTable(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { loadTable(); }
        });

        // Gắn sự kiện cho 3 nút
        btnThem.addActionListener(this::btnThemActionPerformed);
        btnMoFile.addActionListener(this::btnMoFileActionPerformed);
        btnXoa.addActionListener(this::btnXoaActionPerformed);
    }

    /** Nạp dữ liệu vào bảng, có lọc theo từ khóa tìm kiếm */
    public void loadTable() {
        String key = txtTimKiem.getText().toLowerCase().trim();
        tableModel.setRowCount(0);
        int idx = 1;
        for (TaiLieu tl : AppContext.DATA_SERVICE.layTatCaTaiLieu()) {
            if (!key.isBlank()
                    && !tl.getTenFile().toLowerCase().contains(key)
                    && !tl.getMaDeTai().toLowerCase().contains(key)) continue;
            tableModel.addRow(new Object[]{
                idx++, tl.getTenFile(), tl.getLoai(),
                tl.getMaDeTai(), tl.getNgayThem(), tl.getGhiChu()
            });
        }
    }

    /** Lấy phần mở rộng (đuôi file) */
    private String getExtension(String name) {
        int i = name.lastIndexOf('.');
        return i >= 0 ? name.substring(i + 1) : "";
    }

    // ---- Xử lý 3 nút ----

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        chooser.setDialogTitle("Chọn tài liệu cần thêm vào kho");
        if (chooser.showOpenDialog(this) != javax.swing.JFileChooser.APPROVE_OPTION) return;

        // Chọn đề tài liên kết (tùy chọn)
        String selectedMa = "";
        String[] ds = AppContext.DATA_SERVICE.layTatCa().stream()
                .map(d -> d.getMaDT() + " - " + d.getTenDT())
                .toArray(String[]::new);
        if (ds.length > 0) {
            Object choice = javax.swing.JOptionPane.showInputDialog(this,
                    "Liên kết với đề tài (bỏ qua nếu không cần):",
                    "Chọn đề tài", javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null, ds, ds[0]);
            if (choice != null) {
                String s = choice.toString();
                selectedMa = s.contains("-") ? s.split("-")[0].trim() : s.trim();
            }
        }

        String today = new SimpleDateFormat("dd/MM/yyyy").format(new Date());
        File[] files = chooser.getSelectedFiles();
        for (File f : files) {
            String ext = getExtension(f.getName()).toUpperCase();
            String loai = switch (ext) {
                case "PDF"        -> "PDF";
                case "DOC", "DOCX" -> "Word";
                case "XLS", "XLSX" -> "Excel";
                case "PPT", "PPTX" -> "PowerPoint";
                default           -> "Khác";
            };
            TaiLieu tl = new TaiLieu(UUID.randomUUID().toString(),
                    f.getName(), f.getAbsolutePath(), loai, selectedMa, today);
            AppContext.DATA_SERVICE.themTaiLieu(tl);
        }
        loadTable();
        javax.swing.JOptionPane.showMessageDialog(this,
                "Đã thêm " + files.length + " tài liệu vào kho!",
                "Thành công", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    private void btnMoFileActionPerformed(java.awt.event.ActionEvent evt) {
        int row = tblTaiLieu.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Vui lòng chọn tài liệu cần mở từ bảng.",
                "Chưa chọn", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        String ten = tableModel.getValueAt(row, 1).toString();
        for (TaiLieu tl : AppContext.DATA_SERVICE.layTatCaTaiLieu()) {
            if (tl.getTenFile().equals(ten)) {
                try {
                    File f = new File(tl.getDuongDan());
                    if (!f.exists()) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                            "File không còn tồn tại tại:\n" + tl.getDuongDan(),
                            "Không tìm thấy file", javax.swing.JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    java.awt.Desktop.getDesktop().open(f);
                } catch (Exception ex) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                        "Không thể mở file:\n" + ex.getMessage(),
                        "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
                return;
            }
        }
    }

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {
        int row = tblTaiLieu.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Vui lòng chọn tài liệu cần xóa từ bảng.",
                "Chưa chọn", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Xóa tài liệu này khỏi kho?\n(File gốc trên máy sẽ không bị xóa)",
            "Xác nhận xóa",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        String ten = tableModel.getValueAt(row, 1).toString();
        AppContext.DATA_SERVICE.layTatCaTaiLieu().stream()
                .filter(t -> t.getTenFile().equals(ten))
                .findFirst()
                .ifPresent(tl -> AppContext.DATA_SERVICE.xoaTaiLieu(tl.getId()));
        loadTable();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoFile;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tblTaiLieu;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
